MONTHLY_RULES = {
    "SHIFT_START_MINUTES": 9 * 60 + 30,
    "SHIFT_END_MINUTES": 18 * 60 + 30,
    "FULL_DAY_MINUTES": 9 * 60,
    "GRACE_MINUTES": 10,
    "FULL_DAY_REQUIRED_MINUTES": 8 * 60 + 50,
    "HALF_DAY_MINIMUM_MINUTES": 3 * 60,
    "LESS_HOURS_RULE_MINIMUM_MINUTES": 6 * 60,
    "OVERTIME_START_MINUTES": 9 * 60 + 15,
    "ROUNDING_INTERVAL_MINUTES": 15,
    "SALARY_CALCULATION_DAYS": 30,
    "SALARY_HOURS_PER_DAY": 9,
    "LEAVE_EARN_DIVISOR": 12,
}
